<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Cityzen" failures="1" tests="2" name="Always Run Test" time="0.013" errors="0" timestamp="2024-06-09T01:18:52 EDT">
  <testcase classname="testngproject.AlwaysRunTest" name="test1" time="0.003">
    <failure type="java.lang.AssertionError" message="Failing this test on purpose">
      <![CDATA[java.lang.AssertionError: Failing this test on purpose
at testngproject.AlwaysRunTest.test1(AlwaysRunTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testngproject.AlwaysRunTest" name="test2" time="0.002"/>
</testsuite> <!-- Always Run Test -->
